title: Jocelyn Pern
logo: /assets/img/headshot_circle.png
description: Mechanical Engineering Student
#show_downloads: true
theme: jekyll-theme-minimal

sass:
  style: compressed
markdown: kramdown

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default
